### ISSUE TITLE
nginx configuration template

### ISSUE THREAD

**Issue by matthaes** [svenlahann/vagrant-ansible#6]
as default in current state it is php 5.6 selected on project. under nginx configuration is a php7 socket reference. It should php5.6.

environment/roles/webserver/templates/nginx.j2
`location ~ \.php$ {
		include snippets/fastcgi-php.conf;
	#
	#	# With php7.0-cgi alone:
	#	fastcgi_pass 127.0.0.1:9000;
	#	# With php7.0-fpm:
	#	fastcgi_pass unix:/run/php/php7.0-fpm.sock;
		fastcgi_pass unix:/run/php/php5.6-fpm.sock;
	}`

**Comment by svenlahann** [comment]
fixed, added multiple nginx templates for php5.6 and php7.0
